### ISSUE TITLE
Schedule a Meet with GDSC Lead

### ISSUE THREAD

**Issue by gajjararyan** [oscfcommunity/GCCD2024#29]
## Task Title
- **Description**: We are organizing meet or a short call for all GDSC Lead in Gujarat to partner with or to help in our reach.
- **Assignee**: Task to complete with Neel bhai, Khushal and Darshan @gajjararyan .
- **Priority**:  Medium 
- **Due Date**: Before the 21 July 2024

## Checklist
- [x] Connect with GDSC Lead
- [x] Schedule one call
- [ ] Finalized all things with Lead

## Additional Notes
Add any additional information or context here.

**Comment by neelshah2409** [comment]
Steps / Criteria for GDSC Leads:

 -  Rollout email from your community forum.
 -   We would be giving 40 % exculsive off unique coupon code for each college or GDSC club which can be reddem by 50 participants.
-  If more than 20 tickets are sold by this coupon code then GDSC lead gets the free ticket.

**Comment by gajjararyan** [comment]
https://docs.google.com/spreadsheets/d/1KUvEXlGraTOAtOuSduhl3I2FbQqsHl10knjaReVKKk0/edit?usp=sharing

@neelshah2409  this is the link which we are sharing to GDSC Lead, just check once
