### ISSUE TITLE
Sharing the Community Partner form and Awareness of tickets discount

### ISSUE THREAD

**Issue by gajjararyan** [oscfcommunity/GCCD2024#35]
## Task Title
- **Description**: We need to share the Community Partner form with various communities. Additionally, we should raise awareness about ticket discounts. Let's ensure we reach out to communities in and around Gujarat.
- **Assignee**: @gajjararyan 
- **Priority**: Medium
- **Due Date**: ASAP.

## Checklist
- [x] Identify and Target Communities
- [x] Share via Multiple Channels
- [x] Personalize Outreach
- [x] Follow Up and response

## Additional Notes
🙌🚀.
